Remove newline characters from JSON
In some cases (did not figure out when and when not), toJSON leads to representations like

    > toJSON(x_2)
    [1] "[ [\n \"Scenario\",\n\"Waterbody\", ....

instead of

    > toJSON(x_1)
    [1] "[ [ \"Scenario\", \"Waterbody\", ...

which makes python.assign fail with the message

    SyntaxError: EOL while scanning string literal

This can be avoided by substituting the newline characters in the JSON string before it is passed to the Python interpreter.